# Generated by Django 3.1.4 on 2021-03-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='years',
            field=models.CharField(default='2019', max_length=100),
            preserve_default=False,
        ),
    ]
